### ISSUE TITLE
Requirements and how to test each procedure

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-tests#15]
This issue is meant to discuss what requirements each procedure needs - if it depends on other procedures or some other stuff.

### API_ListEntities
* Test 1: See if it doesn't return an error.
* Requirements: Doesn't seem to depend on anything.

### InsertNewEntity
* Test 1: See if it doesn't return an error.
* Test 2: Check if it's inserting - list the entities, keep the number of returned rows, insert a new entity, list the entities and check if the returned rows are +1.
* Requirements: API_ListEntities

Discuss and populate it, info will be appended to organize this better.

**Comment by migsilva95** [comment]
@L0cust API_ListEntities; InsertNewEntity; API_InsertNewAdmin; API_IsAdmin; API_UserExists; API_InsertNewUser
@asantos3 API_InsertNewProject; API_InsertNewProjectRevision; API_InsertNewProjectRevisionEntity; API_InsertNewProjectRevisionLog; API_InsertNewProjectRevisionLogDoc
@Freakmania API_InsertNewApplication; API_InsertNewApplicationAttribute; API_InsertNewAtribute; API_InsertNewFunction; API_LoginChallenge
@migsilva95 API_InsertNewSchool; API_InsertNewSchoolEntity; API_InsertProjectWeb; API_ListProjects;

**Comment by migsilva95** [comment]
Here is my part of the work:

### API_InsertNewSchool

* Test 1: See if it doesn't return an error.
* Test 2: Check if it's inserting - list the schools, keep the number of returned rows, insert a new school, list the schools and check if the returned rows are +1.
* Requirements: Doesn't seem to depend on anything.

### API_InsertNewSchoolEntity

* Test 1: See if it doesn't return an error.
* Test 2: Check if it's inserting - list the SchoolEntity, keep the number of returned rows, insert a new SchoolEntity, list the SchoolEntity and check if the returned rows are +1.
* Requirements: Depend of table school.

### API_InsertProjectWeb

* Test 1: See if it doesn't return an error.
* Test 2: Check if it's inserting - list the application, keep the number of returned rows, insert a new application, list the application and check if the returned rows are +1.
* Requirements: Depend of table entity.

### API_ListProjects

* Test 1: See if it doesn't return an error.
* Test 2: Check if it's listing.
* Requirements: Denpend of tables application, project, applicationattribute and attribute.

**Comment by asantos3** [comment]
Updated @migsilva95 comments due to **API_InsertNewUser** already being half-baked by @L0cust. There's also no point of having two devs working on API_UserExists and API_InsertNewUser at the same time, one for both should be better.

**Comment by ghost** [comment]
### InsertNewEntity
* Test 1: See if it doesn't return an error.
* Test 2: Check if it's inserting - list the entities, keep the number of returned rows, insert a new entity, list the entities and check if the returned rows are +1.
* Requirements: API_ListEntities

### API_InsertNewUser
* Test 1: See if it doesn't return an error.
* Test 2: Check if it's inserting - list the student or teacher depending of type, keep the number of returned rows, insert new student or teacher depending of type, list the student or teacher depending of type and check if the returned rows are +1.
* Requirements: Depends of tables student and teacher.

**Comment by asantos3** [comment]
Closed due to the database having to be restrucured. If new procedures are made in the new version we should just open a new issue.
